language: cpp
compiler:
  - gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get install qt4-dev-tools libvtk5-dev libvtk5-qt4-dev libnetcdf-dev libshp-dev libgeotiff-dev
script: "mkdir build && cd build && cmake -DOGS_BUILD_QT=ON .. && cmake .. && make"
notifications:
  email:
    - lars.bilke@ufz.de
