sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

cache:
  ccache: true
  directories:
    - $HOME/cmake-3.1.1-Linux-x86_64
    - $HOME/.conan

git:
  lfs_skip_smudge: true

env:
  global:
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - PATH=$HOME/cmake-3.1.1-Linux-x86_64/bin:$PATH
matrix:
  include:
    - compiler: gcc
      env: CASE=CLI CMAKE_ARGS="-DOGS_BUILD_UTILS=ON"
    - compiler: gcc
      env: CASE=GUI CMAKE_ARGS="-DOGS_BUILD_GUI=ON -DOGS_BUILD_CLI=OFF -DOGS_BUILD_TESTS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON"

before_install:
  - bash scripts/travis/cmake.sh
  - bash scripts/travis/conan.sh
  - git lfs pull --exclude "web/**,Tests/Data/**"
  - git lfs pull --include "Tests/Data/FileIO/**,Tests/Data/MathLib/**"

script:
  - mkdir build; cd build
  - CC=gcc-4.9 CXX=g++-4.9 cmake $CMAKE_ARGS -DOGS_USE_CONAN=ON -DOGS_CONAN_BUILD=never -DOGS_USE_PCH=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j 2
  - if [ "${CASE}" == "CLI" ]; then make tests; fi
